FROM ubuntu:latest
MAINTAINER Mark Phillips (mark.phillips@gmail.com)
LABEL version="0.5"
LABEL description="Dockerfile XMRigCC Server 2.0, for macOS"

RUN apt-get update && \
	apt install git build-essential libbz2-dev cmake libuv1-dev libssl-dev libhwloc-dev wget gcc g++ -y && \
	apt clean && \
        rm -rf /var/lib/apt/lists/*

RUN  git clone https://github.com/Bendr0id/xmrigCC.git && \
	cd xmrigCC && \
	git checkout dev && \
	cmake . && \
	make

COPY Dockerfile /Dockerfile
COPY docker-wrapper.sh /

WORKDIR /xmrigCC

RUN chmod +x /docker-wrapper.sh && \
	useradd docker && \
	mkdir /home/docker && \
	chown docker:docker /home/docker

USER docker
ENTRYPOINT  ["/docker-wrapper.sh"]

